const express = require('express');
const cors = require('cors');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const PDFDocument = require('pdfkit'); // Back to standard pdfkit for simplicity
const { runAgent1, runAgent2, runAgent3, runAgent4, runAgent5 } = require('./agents');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, '../frontend/dist')));

const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    const uploadDir = path.join(__dirname, 'uploads');
    if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir);
    cb(null, uploadDir);
  },
  filename: (req, file, cb) => {
    cb(null, Date.now() + '-' + file.originalname);
  }
});
const upload = multer({ storage });

async function generatePDF(report, outputPath) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(outputPath);
      doc.pipe(stream);

      // Header
      doc.fontSize(20).text('BidIQ Estimate Report', { align: 'center' });
      doc.fontSize(14).text(report.title, { align: 'center' });
      doc.fontSize(10).text(`Generated on: ${report.date}`, { align: 'center' });
      doc.moveDown();

      // 1. Project Overview
      doc.fontSize(16).text('1. PROJECT OVERVIEW');
      doc.fontSize(12).text(`Project Name: ${report.overview.name}`);
      doc.text(`Type: ${report.overview.type}`);
      doc.text(`Location: ${report.overview.location}`);
      doc.text(`Summary: ${report.overview.summary}`);
      doc.text('Assumptions:');
      report.overview.assumptions.forEach(a => doc.text(`- ${a}`));
      doc.moveDown();

      // 2. Summary
      doc.fontSize(16).text('2. ESTIMATE SUMMARY');
      doc.fontSize(12).text(`Materials: ${report.summaryTable.materials}`);
      doc.text(`Labor: ${report.summaryTable.labor}`);
      doc.text(`Permits: ${report.summaryTable.permits}`);
      doc.text(`Contingency: ${report.summaryTable.contingency}`);
      doc.fontSize(14).text(`TOTAL BID RANGE: ${report.summaryTable.totalBidRange}`, { bold: true });
      doc.moveDown();

      // 3. Materials
      doc.fontSize(16).text('3. MATERIALS BREAKDOWN');
      report.materials.forEach(m => {
        doc.fontSize(10).text(`${m.item} (${m.quantity} ${m.unit}): ${m.costRange}`);
      });
      doc.moveDown();

      // 4. Labor
      doc.fontSize(16).text('4. LABOR BREAKDOWN');
      report.labor.forEach(l => {
        doc.fontSize(10).text(`${l.trade} (${l.hours}): ${l.totalCostRange}`);
      });
      doc.moveDown();

      // 5 & 6 Risks and Missing
      doc.fontSize(16).text('5. RISK FLAGS');
      report.risks.forEach(r => doc.fontSize(10).text(`[ ] ${r}`));
      doc.moveDown();

      doc.fontSize(16).text('6. MISSING ITEMS');
      report.missingItems.forEach(m => doc.fontSize(10).text(`[ ] ${m}`));
      doc.moveDown();

      // Footer
      doc.fontSize(8).text('Disclaimer: This estimate is generated by AI for planning purposes. All figures should be verified by a licensed contractor before submitting a formal bid.', 50, doc.page.height - 50, { align: 'center' });

      doc.end();
      stream.on('finish', resolve);
      stream.on('error', reject);
    } catch (err) {
      reject(err);
    }
  });
}

app.post('/api/estimate', upload.fields([{ name: 'plans' }, { name: 'scope' }]), async (req, res) => {
  try {
    const { projectType, location, tradeType, scopeOfWork } = req.body;
    const a1Result = await runAgent1({ projectType, location, tradeType, scopeOfWork });
    const [a2Result, a3Result] = await Promise.all([runAgent2(a1Result), runAgent3(a1Result)]);
    const a4Result = await runAgent4({ a1Result, a2Result, a3Result });
    const a5Result = await runAgent5({ a1Result, a2Result, a3Result, a4Result });

    const pdfFilename = `report-${Date.now()}.pdf`;
    const pdfPath = path.join(__dirname, 'uploads', pdfFilename);
    await generatePDF(a5Result.report, pdfPath);

    res.json({ success: true, report: a5Result.report, pdfUrl: `/api/download/${pdfFilename}` });
  } catch (error) {
    console.error(error);
    res.status(500).json({ success: false, error: error.message });
  }
});

app.get('/api/download/:filename', (req, res) => {
  const filePath = path.join(__dirname, 'uploads', req.params.filename);
  if (fs.existsSync(filePath)) res.download(filePath);
  else res.status(404).send('File not found');
});

app.use((req, res) => res.sendFile(path.join(__dirname, '../frontend/dist/index.html')));

app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
